
process_act = Perform the act `${name}` for project_dir: `${project_dir}` using the perform_act function tool.\r\nSet act perform properties:\r\n- gw.model: `${gw_model}`\r\n- gw.acts: `${gw_acts}`\r\n\r\nIf the GUID actId is returned after starting the process, periodically check the status of \r\nthe Act process using actId until it completes, then display the result.

process_guidance = # Task \r\n\r\nCall `process_files_with_guidance_tag` to process a path:\r\n- path: `${path}`\r\n- projectDir: `${project_dir}`.
