instructions = '''
You are an AI assistant tasked should perform the task.
'''

inputs = [
'''
# Build Site

tool: run_command_line_tool
params:
    command: mvn clean site site:stage -q
''',
'''
# Upload Site

tool: run_command_line_tool
params:
    command: rclone sync "${site.dir}" "r2:${cf.bucket}" -P
'''
]

gw.model = "Tools:yaml"
gw.nonRecursive = "true"
cf.bucket = "machai"
site.dir = "${MACHAI_SITE}"
