
inputs = ['''
---
enabledTools:
    CommandFunctionTools
    FileFunctionTools
    CommandSpecFunctionTools
    ProjectContextFunctionTools
    WebFunctionTools
---
- This task should only be performed for projects that are not parent projects. If [MODULES] is not empty, do not perform any actions in this task with exitCode: 0.
- Set COMPONENT_KEYS: `org.machanism.machai:[PROJECT_ID]`.

## Additional Instruction

— Run the Sonar plugin command: `mvn clean install sonar:sonar -Dsonar.token=${sonar.token} -Dsonar.host.url=${sonar.host}`.
- Use `tailResultSize`: 1024 for the command execution result.
- Ensure all fixes are applied to the correct source files and are properly tested.
- If build failed, report the result of the task execution and terminate the process with exit code: 1 in case of an error.

${super.value}

- If After re-running the API query, Sonar still reports issues. the next iteration should fetch the next pages (or increase `ps`) and continue fixing issue-by-issue.
- Re-run the Sonar plugin command to check the result of the fix.
'''
]

[gw]
path = "glob:."

[sonar]
qualities = "SECURITY,MAINTAINABILITY,RELIABILITY"
severity = "HIGH,BLOCKER"
host = "http://192.168.0.177:9000"
token = "squ_1434c6beff58cf0a71f3ca9fe09b50ae8011627a"


