
inputs = ['''

## Additional Instruction

— Run the Sonar plugin command: `mvn clean install sonar:sonar -Dsonar.token=${sonar.token} -Dsonar.host.url=${sonar.host}`.
- Use `tailResultSize`: 1024 for the command execution result.
- Ensure all fixes are applied to the correct source files and are properly tested.
- This task should only be performed for projects that are not parent projects. If [Child Projects] contain modules, do not perform any actions in this task with exitCode: 0.
- Determine the correct value for [COMPONENT_KEYS] based on the `Project Layout` parameters:
  - If [Modules]: `<NOT_DEFINED_VALUE>`: set `COMPONENT_KEYS` to `org.machanism.machai:[Project Identifier]` else set `COMPONENT_KEYS` to `[Project Identifier]`.

%s

— Re-run the Sonar plugin command: `mvn clean install sonar:sonar -Dsonar.token=${sonar.token} -Dsonar.host.url=${sonar.host}`.
- If After re-running the API query, Sonar still reports issues. the next iteration should fetch the next pages (or increase `ps`) and continue fixing issue-by-issue.
— Re-run the Sonar plugin command to check the result of the fix.
'''
]

[gw]
scanDir = "glob:."

[sonar]
qualities = "SECURITY,MAINTAINABILITY,RELIABILITY"
severity = "LOW,MEDIUM,HIGH,BLOCKER"
host = "http://192.168.0.177:9000"
token = "squ_3c0d75d3b5cddf631913b5a21eda70048706ad00"


