description = "Automated unit test generation and SonarQube coverage reporting."

basedOn = "unit-tests"

inputs = '''
%s

- Use `tailResultSize`: 1024 for the command execution result.
- **After test creation or updates are complete—either because the coverage threshold is met or further improvement is not possible—run the Sonar Maven plugin:**  
  Execute:  
  ```
  mvn sonar:sonar \
    -Dsonar.token=${sonar.token} \
    -Dsonar.host.url=http://${sonar.host} \
  ```
- Report the result of the task execution, terminate the process with exit code: 1 in case of an error.
'''

severities="LOW,MEDIUM,HIGH,BLOCKER"
sonar.host="192.168.0.177:9000"
sonar.token="squ_3c0d75d3b5cddf631913b5a21eda70048706ad00"


