description = "Automated unit test generation and SonarQube coverage reporting."

basedOn = "unit-tests"

inputs = '''
%s

- **After test creation or updates are complete—either because the coverage threshold is met or further improvement is not possible—run the Sonar Maven plugin:**  
  Execute:  
  ```
  mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
    -Dsonar.token=${sonar.token} \
    -Dsonar.host.url=http://${sonar.host} \
    -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  ```
'''

severities="LOW,MEDIUM,HIGH,BLOCKER"
sonar.host="192.168.0.177:9000"
sonar.token="sqa_1ca2fc4cb0449e8a70c08933bb8a82cba89d91df"


