inputs = [
'''
# Upload Site

tool: run_command_line_tool
params:
    command: java -version
    dir: .
    env: 
        a: b

''']

gw.model = "Tools:yaml"
gw.nonRecursive = "true"
cf.bucket = "machai"
site.dir = "${MACHAI_SITE}"
