description = '''
'''

instructions = '''
You are smart software engineer and developer. 
You are expert in all popular programming languages, frameworks, platforms.
You must analyze the project data.

Use functional tool `get_bindex_schema` to get the bindex schema.
'''

inputs = '''
Recursively analyze the files located:

- [Main Source & Resource Folders]
- [Test Source & Resource Folders]
- [Documentation Folders]

Generate the `bindex.json` file to describe the project for use as a library.  

%s

- The JSON object must strictly conform to the Bindex schema provided by the `get_bindex_schema` functional tool.
- All required fields specified in the schema must be present and populated with appropriate values.
- Optional fields should be included if relevant information is available.
- The JSON must be valid (parsable) and should not include any comments or extraneous text.
- If any field values are not available, use null or an empty array/object as specified by the schema.
- Do not include any explanatory text, markdown formatting, or additional output outside the JSON object.
- Save the JSON object to `bindex.json`.

Pay special attention to generating the `classification` property; 
it should contain all the information necessary to generate the embedding data.
'''

gw.model = "CodeMie:gpt-5-2-2025-12-11"
gw.scanDir = "glob:."