services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db
      - mongodb_mongot:/data/mongot
      
  bindex-repo-app:
    image: eclipse-temurin:17-jre
    container_name: bindex-repo-app
    environment:
      - BINDEX_PASSWORD=pass
      - BINDEX_REPO_URL=mongodb://mongodb:27017/?appName=machanism
      - BINDEX_USER=user
      - GENAI_PASSWORD=${GENAI_PASSWORD}
      - GENAI_USERNAME=${GENAI_USERNAME}
      - gw_model=CodeMie:gpt-5.4-2026-03-05
      - embedding_model=CodeMie:text-embedding-005
    command: >
      sh -c "java -cp /app/machai-mcp-server.jar:/app/bindex-core.jar org.machanism.machai.mcp.server.McpServer --port 45000"
    ports:
      - 45000:45000
    volumes:
      - ./appdata:/app   
    depends_on:
      - mongodb
      
volumes:
  mongodb_config:
  mongodb_data:
  mongodb_mongot: