package org.machanism.machai.ai.manager;

/**
 * Immutable token-usage metrics for a single generative AI interaction.
 *
 * <p>A usage instance captures the number of prompt tokens, cached prompt tokens,
 * and completion tokens reported by a provider for one request-response cycle.
 * These values can be collected by {@link UsageStatistics} to produce aggregated
 * reporting per model.
 */
public class Usage {

	/**
	 * Number of input or prompt tokens consumed by the request.
	 */
	private final long inputTokens;

	/**
	 * Number of cached input tokens reported by the provider.
	 */
	private final long inputCachedTokens;

	/**
	 * Number of output or completion tokens produced by the request.
	 */
	private final long outputTokens;

	/**
	 * Creates a usage record.
	 *
	 * @param inputTokens       the number of input tokens consumed by the request
	 * @param inputCachedTokens the number of cached input tokens reused by the
	 *                          provider
	 * @param outputTokens      the number of output tokens generated in the response
	 */
	public Usage(long inputTokens, long inputCachedTokens, long outputTokens) {
		this.inputTokens = inputTokens;
		this.inputCachedTokens = inputCachedTokens;
		this.outputTokens = outputTokens;
	}

	/**
	 * Returns the number of input tokens consumed by the request.
	 *
	 * @return the input token count
	 */
	public long getInputTokens() {
		return inputTokens;
	}

	/**
	 * Returns the number of cached input tokens reported by the provider.
	 *
	 * @return the cached input token count
	 */
	public long getInputCachedTokens() {
		return inputCachedTokens;
	}

	/**
	 * Returns the number of output tokens generated by the response.
	 *
	 * @return the output token count
	 */
	public long getOutputTokens() {
		return outputTokens;
	}

}
